addpath(genpath("C:\Users\Niflheim\Documents\GitHub\External\CellExplorer"))
% set session
basepath = "\\oak-smb-giocomo.stanford.edu\groups\giocomo\export\data\Projects\JohnKei_NPH3";
load('\\oak-smb-giocomo.stanford.edu\groups\giocomo\fkmasuda\fkm_analysis\EAJ_revisions\wt_ket_sessions.mat')
for s = 1:length(wt_ket_sessions)
    datadir = sprintf('%s\\%s\\%s_keicontrasttrack_ketamine1_g0\\%s_keicontrasttrack_ketamine1_g0_imec0',...
        basepath,wt_ket_sessions{s,1},wt_ket_sessions{s,2},wt_ket_sessions{s,2});
    cd(datadir)

    % set params
    session = sessionTemplate(datadir);
    session.extracellular.fileName = [wt_ket_sessions{s,2},'_keicontrasttrack_ketamine1_g0_t0.imec0.ap.bin'];
    
    % generate metrics file
    cell_metrics = ProcessCellMetrics('session', session,...
        'metrics',{'monoSynaptic_connections'},...
        'includeInhibitoryConnections',true,...
        'manualAdjustMonoSyn',false,...
        'getWaveformsFromDat',false,...
        'showWaveforms',false,...
        'sessionSummaryFigure',false,...
        'showGUI',false);
end